version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app/dockerfile
    volumes:
      - ./src/:/app

  web:
    build: 
      context: .
      dockerfile: ./docker/web/dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
    
  db:
    build: 
      context: .
      dockerfile: ./docker/db/dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE: mobile_app
      - MYSQL_USER: mobileOrder 
      - MYSQL_PASSWORD: "mobileOrder#321" 
      - MYSQL_ROOT_PASSWORD: "Hryt@3227" 
      - TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:

